dist: bionic
group: travis_latest
sudo: true

os: linux
language: python

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-10
    - cmake
    - ninja-build
    - libstdc++-8-dev
    - python3-pip
    update: true

matrix:
  include:
    - env: CXX=clang++-10

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libpulse-dev

install:
  - sudo python3 -m pip install meson
  - git clone https://github.com/SCOTT-HAMILTON/FakeLib
  - cd FakeLib
  - mkdir build
  - meson build
  - ninja -C build
  - sudo ninja -C build install
  - cd ..

script:
  - mkdir build
  - meson build
  - ninja -C build

